SEED = 12345

MAP_SIZE = 10000

# GRAPH
GRAPH_MAX_POINTS = 7500
GRAPH_RELAXATIONS = 2
POINT_RADIUS = 15

# GEO
STARTING_LAND = True
STARTING_LAND_SIZE = 5000
STARTING_LAND_POS = (5000, 5000)

LAND_PERLIN_WEIGHT = 1.25
LAND_RADIAL_WEIGHT = 1.1
LAND_THRESHOLD = 1.0
LAND_CORNER_FACTOR = 0.3

ELEVATION_OCEAN_WEIGHT = .8
ELEVATION_PERLIN_WEIGHT = 1.25

RANDOM_LAKE_FACTOR = 0.03
LAND_MASS_CULL_SIZE = 15

DRAW_CORNERS = False
DRAW_REGION_OUTLINE = True
REGION_OUTLINE_WIDTH = 10

DRAW_ELEVATION_ON_REGIONS = False
DRAW_DISTANCE_FROM_OCEAN_REGIONS = False
DRAW_DISTANCE_FROM_WATER_REGIONS = False
DRAW_DISTANCE_FROM_OCEAN_CORNERS = False
DRAW_DISTANCE_FROM_WATER_CORNERS = False

DRAW_REGIONS_NORMAL = False
DRAW_REGIONS_ELEVATION = False
DRAW_REGIONS_ELEVATION_COLORED = True
DRAW_REGIONS_OCEAN_DISTANCE = False
DRAW_REGIONS_WATER_DISTANCE = False

# GUI
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800

BUTTON_BUFFER = 10
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50
BUTTON_FONT = 'ariel'
BUTTON_FONT_SIZE = 20
BUTTON_RESET_TIME = 0.1

VIEWPORT_MOVING_SPEED = 200
VIEWPORT_MAX_ZOOM = 8
VIEWPORT_SIZE = 800
